### ISSUE TITLE
rename the project to something specific? 

### ISSUE THREAD

**Issue by fangq** [fNIRS/snirf_homer3#1]
hi @jayd1860, there will be multiple parsers for each language, I suggest you to give your parser a name, such as homer3snirf, or anything you want, just make it easier to link to the main repo.

**Comment by jayd1860** [comment]
That's a good idea. I'll rename it.

**Comment by jayd1860** [comment]
I renamed it to snirf_homer3 (haven't pushed back the change yet). Will that work for the linking?

**Comment by fangq** [comment]
that sounds fine. I haven't linked it yet, after renaming it, I will link.

you can do that by going to "Settings" on the top-right.

also, consider moving all files from the "SNIRF_ReaderWriter" folder to the root.

**Comment by jayd1860** [comment]
Ok, I renamed it to snirf_homer3. Thanks.

**Comment by fangq** [comment]
what I meant was to rename "snirf-code" to "snirf_homer3", and then remove the subfolder on the root level

**Comment by jayd1860** [comment]
Ok did that. Let me know if this works

**Comment by fangq** [comment]
great. now added it as a submodule to the snirf repo.
https://github.com/fNIRS/snirf/tree/master/lib/matlab

closing this now.

the only other comment is that, I noticed there is a 17MB sample file in your Snirf/Examples folder. Is it updated with the new format? do you need that file? other files are quite small.

**Comment by jayd1860** [comment]
The demo should generate snirf files but they should not be part of the version control. 
If you see snirf files there that is a mistake and I will delete them from the repo.

**Comment by jayd1860** [comment]
Ok I just looked and didn't see any snirf files under Examples so it is as intended. You're just seeing a slightly larger than usual .nirs file which is part of the demo of converting it to .snirf, saving it, and loading it back, then comparing the saved and loaded files to make sure they equal. 

Thanks for checking.
